nav:
  Home: /
  About: /about/

projects_url: https://github.com/brunoalano

customize:
    gravatar:
        email: bruno@neurologic.com.br
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/brunoalano
        twitter: https://twitter.com/brunoalano
        linkedin: https://www.linkedin.com/in/brunoalano/
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: brunoalano-1 # Disqus Comments Shortname
    google_analytics:  # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
